### ISSUE TITLE
Could not use Expected Traces Algorithm

### ISSUE THREAD

**Issue by dubailey** [karush17/Deep-Eligibility-Traces#1]
Hello when trying to run the Expected Traces Algorithm I got many errors from the code.
<img width="729" alt="Screen Shot 2021-09-09 at 2 30 36 PM" src="https://user-images.githubusercontent.com/8495382/132765465-bb0bb120-be65-4f58-aeea-f70a8ba7bc9c.png">

**Comment by dubailey** [comment]
Also how would I be able to get this to work with Atari games?

**Comment by karush17** [comment]
The issue that you were facing was an in-place operation to a variable of the computation graph. This is prohibited in newer versions of torch. I have updated the repo and the code works well now. Here is the output log and return plot on CartPole-v0 environment- 

![output_log](https://user-images.githubusercontent.com/47248974/132927909-d81e937a-9609-436b-a92c-3923bd921b96.png)

![plot_rewards](https://user-images.githubusercontent.com/47248974/132927850-92dd7b32-a045-48e8-96bf-8032f05c0607.png)
)

To answer your second question, you can use the repo for atari RAM environments. However, I myself have not experimented with atari so hyperparameters would have to be tuned. In case you want to run the agent on image observations then you can try the Adam-ify transform trick from [Expected Trace paper](https://arxiv.org/pdf/2007.01839.pdf).  

Closing the issue for now, feel free to open it if you face difficulties.

**Comment by dubailey** [comment]
thank you
